import { Translation, Recipe, Category } from './types';

export const ADMIN_EMAIL = 'admin@kitchen.com';

export const TRANSLATIONS: Record<'ar' | 'he', Translation> = {
  ar: {
    title: 'مطبخ المستعجلين',
    home: 'الرئيسية',
    mainDishes: 'الأطباق الرئيسية',
    sweets: 'الحلويات',
    diet: 'دايت وصحي',
    search: 'ابحث عن وصفة...',
    login: 'تسجيل الدخول',
    register: 'دخول',
    logout: 'تسجيل الخروج',
    addRecipe: 'أضف وصفة',
    edit: 'تعديل الوصفة',
    adminPanel: 'لوحة الإدارة',
    welcome: 'أهلاً بك في مطبخ المستعجلين - وصفات سريعة وسهلة للناس المشغولة!',
    ingredients: 'المكونات',
    steps: 'طريقة التحضير',
    time: 'وقت التحضير',
    author: 'الكاتب',
    city: 'المدينة',
    date: 'تاريخ النشر',
    delete: 'حذف الوصفة',
    noRecipes: 'لا توجد وصفات هنا بعد.',
    placeholderTitle: 'عنوان الوصفة (مثلاً: معكرونة الـ 10 دقائق)',
    placeholderIngredients: 'المكونات (ضع كل مكون في سطر جديد)',
    placeholderSteps: 'الخطوات (ضع كل خطوة في سطر جديد)',
    placeholderCity: 'مدينتك',
    submit: 'نشر الوصفة',
    nickname: 'الاسم المستعار',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    back: 'عودة',
    lazySlogan: 'لأن وقتك غالي، والطبخ لازم يكون سهل!',
    aiHelp: 'مساعدة الذكاء الاصطناعي',
    aiLoading: 'جاري التفكير في وصفة سهلة...',
    communityRecipes: 'وصفات أخرى',
    addYourOwn: 'شاركنا وصفتك السريعة الخاصة',
    uploadPhoto: 'أضف صورة للوصفة',
    translateRecipe: 'ترجمة هذه الوصفة للعربية',
    translating: 'جاري الترجمة...',
    adminBadge: 'أدمن',
    adminNotice: 'يمكن للأدمن حذف وتعديل أي وصفة.',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    fastTime: 'سريع جداً',
    enterTitleAlert: 'يرجى إدخال عنوان أولاً',
    clickToChangePhoto: 'انقر لتغيير الصورة',
    guest: 'ضيف',
  },
  he: {
    title: 'המטבח המהיר',
    home: 'דף הבית',
    mainDishes: 'מנות עיקריות',
    sweets: 'קינוחים ומתוקים',
    diet: 'דיאט ובריאות',
    search: 'חפש מתכון...',
    login: 'התחברות',
    register: 'כניסה',
    logout: 'התנתקות',
    addRecipe: 'הוסף מתכון',
    edit: 'עריכת מתכון',
    adminPanel: 'ניהול',
    welcome: 'ברוכים הבאים למטבח המהיר - מתכונים קלים ומהירים לאנשים עסוקים!',
    ingredients: 'מצרכים',
    steps: 'שלבי הכנה',
    time: 'זמן הכנה',
    author: 'כותב/ת',
    city: 'עיר',
    date: 'תאריך פרסום',
    delete: 'מחק מתכון',
    noRecipes: 'אין עדיין מתכונים בקטגוריה זו.',
    placeholderTitle: 'שם המתכון (למשל: פסטה ב-10 דקות)',
    placeholderIngredients: 'מצרכים (כל מצרך בשורה חדשה)',
    placeholderSteps: 'שלבי הכנה (כל שלב בשורה חדשה)',
    placeholderCity: 'העיר שלך',
    submit: 'פרסם מתכון',
    nickname: 'כינוי',
    email: 'אימייל',
    password: 'סיסמה',
    back: 'חזרה',
    lazySlogan: 'כי הזמן שלך יקר, והבישול חייב להיות פשוט!',
    aiHelp: 'עזרת בינה מלאכותית',
    aiLoading: 'חושב על מתכון קל עבורך...',
    communityRecipes: 'מתכונים נוספים מהקהילה שלנו',
    addYourOwn: 'שתפו אותנו במתכון המהיר שלכם',
    uploadPhoto: 'הוסף תמונה למתכון',
    translateRecipe: 'תרגם את המתכון לעברית',
    translating: 'מתרגם...',
    adminBadge: 'אדמין',
    adminNotice: 'אדמין יכול למחוק ולערוך כל מתכון.',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק?',
    fastTime: 'מהיר מאוד',
    enterTitleAlert: 'נא להזין כותרת תחילה',
    clickToChangePhoto: 'לחץ לשינוי תמונה',
    guest: 'אורח',
  },
};

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'معكرونة سريعة بالجبن',
    category: 'main',
    ingredients: ['200 جرام معكرونة', 'كوب جبن مبشور', 'ملح وفلفل'],
    steps: ['اغلي المعكرونة', 'أضف الجبن والبهارات', 'قلب وقدم'],
    prepTime: '10 دقائق',
    author: 'أبو العز',
    city: 'عمان',
    date: '2024-05-20',
    userId: 'admin',
    imageUrl: 'https://picsum.photos/seed/pasta/400/300',
    originalLang: 'ar',
    translations: {
      he: {
        title: 'פסטה מהירה עם גבינה',
        ingredients: ['200 גרם פסטה', 'כוס גבינה מגורדת', 'מלח ופלפל'],
        steps: ['להרתיח את הפסטה', 'להוסיף גבינה ותבלינים', 'לערבב ולהגיש'],
        prepTime: '10 דקות'
      }
    }
  },
  {
    id: '2',
    title: 'פנקייק בננה מהיר',
    category: 'sweets',
    ingredients: ['2 בננות בשלות', '2 ביצים', 'מעט קינמון'],
    steps: ['למעוך את הבננות', 'לערבב עם הביצים', 'לטגן במחבת קטנה'],
    prepTime: '5 דקות',
    author: 'דנה',
    city: 'תל אביב',
    date: '2024-05-21',
    userId: 'admin',
    imageUrl: 'https://picsum.photos/seed/pancake/400/300',
    originalLang: 'he',
    translations: {
      ar: {
        title: 'بان كيك موز سريع',
        ingredients: ['2 موز ناضج', '2 بيض', 'القليل من القرفة'],
        steps: ['اهرسي الموز', 'اخلطي مع البيض', 'اقلي في مقلاة صغيرة'],
        prepTime: '5 دقائق'
      }
    }
  }
];