
import { Translation, Recipe, Category } from './types';

export const ADMIN_EMAIL = 'rihan.rm52@gmail.com';

export const TRANSLATIONS: Record<'ar' | 'he', any> = {
  ar: {
    title: 'مطبخ المستعجلين',
    home: 'الرئيسية',
    mainDishes: 'الأطباق الرئيسية',
    sweets: 'الحلويات',
    diet: 'أطباق صحية',
    search: 'ابحث عن وصفة...',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    logout: 'تسجيل الخروج',
    addRecipe: 'أضف وصفة',
    edit: 'تعديل الوصفة',
    adminPanel: 'لوحة الإدارة',
    welcome: 'أهلاً بك في مطبخ المستعجلين - وصفات سريعة وسهلة للناس المشغولة!',
    ingredients: 'المكونات',
    steps: 'طريقة التحضير',
    time: 'وقت التحضير',
    author: 'الكاتب',
    city: 'المدينة',
    date: 'تاريخ النشر',
    delete: 'حذف الوصفة',
    noRecipes: 'لا توجد وصفات هنا بعد.',
    placeholderTitle: 'عنوان الوصفة (مثلاً: معكرونة الـ 10 دقائق)',
    placeholderIngredients: 'المكونات (ضع كل مكون في سطر جديد)',
    placeholderSteps: 'الخطوات (ضع كل خطوة في سطر جديد)',
    placeholderCity: 'مدينتك',
    submit: 'نشر الوصفة',
    nickname: 'الاسم المستعار',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    back: 'عودة',
    lazySlogan: 'لأن وقتك غالي، والطبخ لازم يكون سهل!',
    aiHelp: 'مساعدة الذكاء الاصطناعي',
    aiLoading: 'جاري التفكير في وصفة سهلة...',
    communityRecipes: 'وصفات أخرى',
    addYourOwn: 'شاركنا وصفتك السريعة الخاصة',
    uploadPhoto: 'أضف صورة للوصفة',
    translateRecipe: 'ترجمة تلقائية',
    translating: 'جاري المزامنة والترجمة...',
    adminBadge: 'أدمن',
    adminNotice: 'يمكن للأدمن حذف وتعديل أي وصفة. (admin / AR2019!)',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    fastTime: 'سريع جداً',
    enterTitleAlert: 'يرجى إدخال عنوان أولاً',
    guest: 'ضيف',
    contactUs: 'اتصل بنا',
    close: 'إغلاق',
    copyEmail: 'نسخ البريد',
    emailCopied: 'تم النسخ!',
    displayAuthorLabel: 'اسمك الذي سيظهر بالوصفة',
    placeholderAuthor: 'مثلاً: الشيف علي',
    gallery: 'المعرض',
    uploading: 'جاري التحميل...',
  },
  he: {
    title: 'המטבח המהיר',
    home: 'דף הבית',
    mainDishes: 'מנות עיקריות',
    sweets: 'קינוחים ומתוקים',
    diet: 'מנות בריאות',
    search: 'חפש מתכון...',
    login: 'התחברות',
    register: 'הרשמה',
    logout: 'התנתקות',
    addRecipe: 'הוסף מתכון',
    edit: 'עריכת מתכון',
    adminPanel: 'ניהול',
    welcome: 'ברוכים הבאים למטבח המהיר - מתכונים קלים ומהירים לאנשים עסוקים!',
    ingredients: 'מצרכים',
    steps: 'שלבי הכנה',
    time: 'זמן הכנה',
    author: 'כותב/ת',
    city: 'עיר',
    date: 'תאריך פרסום',
    delete: 'מחק מתכון',
    noRecipes: 'אין עדיין מתכונים בקטגוריה זו.',
    placeholderTitle: 'שם המתכון (למשל: פסטה ב-10 דקות)',
    placeholderIngredients: 'מצרכים (כל מצרך בשורה חדשה)',
    placeholderSteps: 'שלבי הכנה (כל שלב בשורה חדשה)',
    placeholderCity: 'העיר שלך',
    submit: 'פרסם מתכון',
    nickname: 'כינוי',
    email: 'אימייל',
    password: 'סיסמה',
    back: 'חזרה',
    lazySlogan: 'כי הזמן שלך יקר, והבישול חייב להיות פשוט!',
    aiHelp: 'עזרת בינה מלאכותית',
    aiLoading: 'חושב על מתכון קל עבורך...',
    communityRecipes: 'מתכונים נוספים מהקהילה שלנו',
    addYourOwn: 'שתפו אותנו בממתכון המהיר שלכם',
    uploadPhoto: 'הוסף תמונה למתכון',
    translateRecipe: 'תרגום אוטומטי',
    translating: 'מסנכרן ומתרגם...',
    adminBadge: 'אדמין',
    adminNotice: 'אדמין יכול למחוק ולערוך כל מתכון. (admin / AR2019!)',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק?',
    fastTime: 'מהיר מאוד',
    enterTitleAlert: 'נא להזין כותרת תחילה',
    guest: 'אורח',
    contactUs: 'צור קשר',
    close: 'סגור',
    copyEmail: 'העתק אימייל',
    emailCopied: 'הועתק!',
    displayAuthorLabel: 'השם שלך שיופיע במתכון',
    placeholderAuthor: 'למשל: השף עלי',
    gallery: 'גלריה',
    uploading: 'מעלה תמונה...',
  },
};

export const INITIAL_RECIPES: Recipe[] = [];
